---
title: ''
output: pdf_document
---

# Conclusions

My analysis revealed complex relationships between students’ sustainability competencies and innovative ESD interventions over time, with the involved group demonstrating higher sustainability attitudes and behaviours one year post-intervention compared to the control group, while also having displayed differences even pre- intervention. These findings highlight the potential of innovative learning and teaching methods within ESD interventions, such as self-regulated and self-directed learning of applicable knowledge and problem-solving skills. I support the latest research advocating for the importance of using long-term empirical data (Waltner et al., 2022) and more robust experimental research designs (Ssossé et al., 2021) to uncover longer-term dynamics that reveal more complex learning outcomes. I further underscored the added value of incorporating efficacy beliefs into the objectives of ESD interventions, as well as in the measurement of sustainability competencies. To fully understand learning outcomes, including real-world behavioural changes, it is insufficient to rely solely on self-reported behaviour intentions and attitudes based on an instrumental understanding of ESD and educational approaches. More nuanced research that distinguishes the capacity for collective agency, as well as the desirability of self-chosen aims and potential external barriers, is necessary. This continued development and empirical research can potentially expand upon the Triple A framework of efficacy beliefs (Hamann et al., 2024). My findings underscore the complexity of measuring sustainability competencies and the heterogeneity of students’ responses to them. Consequently, I support calls for more innovative ESD design as a promising avenue for fostering human agency. Accurately quantifying sustainability competencies in relation to ESD interventions will enhance predictions for more effective educational policymaking in the context of our rapidly changing Anthropocene.